openapi: 3.0.0
info:
  title: API SPOTIFY
  version: 0.0.1
tags:
  - name: musicas
paths:
  /musicas:
    post:
      tags:
        - musicas
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Musicas'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Musicas'
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
    get:
      tags:
        - musicas
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfMusicas'
      security:
        - JWTAuth: []
  /musicas/{id}:
    get:
      tags:
        - musicas
      parameters:
        - in: path
          name: id
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Musicas'
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
    put:
      tags:
        - musicas
      parameters:
        - in: path
          name: id
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Musicas'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Musicas'
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
    delete:
      tags:
        - musicas
      parameters:
        - in: path
          name: id
          schema:
            type: string
      responses:
        '204':
          description: No Content
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
components:
  securitySchemes:
    JWTAuth:
      type: apiKey
      in: header
      name: Authorization
  schemas:
    ArrayOfMusicas:
      type: array
      items:
        $ref: '#/components/schemas/Musicas'
    Musicas:
      type: object
      properties:
        cantor:
          type: string
        nome:
          type: string
    Mensagem:
      type: object
      properties:
        msg:
          type: string
